#!/usr/bin/env bash

source env/bin/activate

if [ $# -eq 0 ]; then
  echo 'Building all sketches'
  echo '---------------------'

  for sketch in $(ls sketches)
  do
    if [ -e sketches/$sketch/template.json ]; then
      echo "Building $sketch..."

      jinja -d sketches/$sketch/template.json ../kylepollina.github.io/templates/sketch.html > sketches/$sketch/tmp.html
      jinja -d sketches/$sketch/template.json sketches/$sketch/tmp.html > sketches/$sketch/$sketch.html
    fi
  done
elif [ $# -eq 1 ]; then
  echo "Building $1..."
  jinja -d sketches/$1/template.json ../kylepollina.github.io/templates/sketch.html > sketches/$1/tmp.html
  jinja -d sketches/$1/template.json sketches/$1/tmp.html > sketches/$1/$1.html
fi
